name: Docker
on:
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opsani/fiber-http
        tag_with_ref: true
        add_git_labels: true
        cache_froms: opsani/fiber-http:${{ steps.extract_branch.outputs.branch }}, opsani/fiber-http:latest
        build_args: BUILDKIT_INLINE_CACHE=1
